defaults: &defaults

  # Strano's public SSH key with which it will attempt to clone Github repos via.
  public_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT22Cz/+S7TuVTlKmmfgY7r8Ghp5cZE07l4qiaRY0QhF10wK7    7jDWNn7ydz981Vjw2Ua2WMrZwY8ichMJfBz5TiQ8dRe4PmsqByeEzvpsVj4b6pInmLuBQJhSKmpwzF5LSoELLhB    +wjU8tbU92kJYUq7x/aRFfo8vyLuJY34yFGx1X3O6M8iVE+FBc8Vaw0zs/9gFXq3YCG1d2LX39oglbeSMflaSve    w7Y6WwvAPU82H3dXc6THDSJJwz9VNMIphr6SacVg253yjq2hi+R2PDYCOMN8+4Al7kALpsCn2gFomQsjJGh6h7n    9Bojwz2Heq8OQ+6E+nj5dJt86iO+N95t belovtorzhok@gmail.com

  # Strano's Github application client ID. See https://github.com/settings/applications
  github_key: 13c08f49f1d690820783

  # Strano's Github application secret. See https://github.com/settings/applications
  github_secret: 3803978cd350b5d458d2c5a31f622783c4377272

  # The path to where Strano will clone your project's repos.
  #
  # clone_path: vendor/repos

  # Allow project creation from repos for Github organization accounts.
  # Default value is true, which allows any and all organizations. Set to
  # false to disallow creating projects from organizations completely.
  # Pass an array of Github organization usernames to restrict which
  # projects Strano can create new projects for.
  #
  # allow_organizations: true
  #
  # To restrict project creation from repos belonging to the 'rails' and
  # 'carlhuda' organizations:
  #
  # allow_organizations: rails, carlhuda

  # Allow project creation from repos for Github user accounts. Default
  # value is true, which allows any and all users. Set to false to disallow
  # creating projects from users completely. Pass an array of Github
  # usernames to restrict which projects Strano can create new projects for.
  #
  # allow_users: true
  #
  # To only allow project creation from your own repos:
  #
  # allow_users: my_github_username

development:
  <<: *defaults

production:
  <<: *defaults
